namespace EMIS.PatientFlow.API.Data
{
	public class Appointment
	{
		public int SlotId { get; set; }

		public string PatientId { get; set; }

		public string PatientIdentifier { get; set; }
		public string Reason { get; set; }

		public string BookedBy { get; set; }

		public string BookingNote { get; set; }

		public string SiteName { get; set; }

		public string SlotName { get; set; }

		public int? DoctorId { get; set; }

		public string SessionDate { get; set; }

		public string SessionTime { get; set; }

		public string SlotStartTime { get; set; }

		public string DoctorName { get; set; }

		public int Duration { get; set; }

		public string ClinicType { get; set; }

		public string Comments { get; set; }
		public string UserName { get; set; }
		public int MemberId { get; set; }
	}
}

	public class EMISWebPA
	{
		//------------------------------------------------------------------------------
		// <auto-generated>
		//     This code was generated by a tool.
		//     Runtime Version:4.0.30319.42000
		//
		//     Changes to this file may cause incorrect behavior and will be lost if
		//     the code is regenerated.
		// </auto-generated>
		//------------------------------------------------------------------------------

		// 
		// This source code was auto-generated by xsd, Version=4.6.1055.0.
		// 

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute("code")]
		[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.e-mis.com/emisopen/MedicalRecord")]
		[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.e-mis.com/emisopen/MedicalRecord", IsNullable=false)]
		public partial class PatientAppointmentList {
    
			private AppointmentStruct[] appointmentField;
    
			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute("Appointment")]
			public AppointmentStruct[] Appointment {
				get {
					return this.appointmentField;
				}
				set {
					this.appointmentField = value;
				}
			}
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute("code")]
		[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.e-mis.com/emisopen/MedicalRecord")]
		public partial class AppointmentStruct {
    
			private int slotIDField;
    
			private int siteIDField;
    
			private string dateField;
    
			private string startTimeField;
    
			private string durationField;
    
			private string notesField;
    
			private string reasonField;
    
			private string sessionNameField;
    
			private int sessionDBIDField;
    
			private HolderStruct[] holderListField;
    
			private string statusField;
    
			/// <remarks/>
			public int SlotID {
				get {
					return this.slotIDField;
				}
				set {
					this.slotIDField = value;
				}
			}
    
			/// <remarks/>
			public int SiteID {
				get {
					return this.siteIDField;
				}
				set {
					this.siteIDField = value;
				}
			}
    
			/// <remarks/>
			public string Date {
				get {
					return this.dateField;
				}
				set {
					this.dateField = value;
				}
			}
    
			/// <remarks/>
			public string StartTime {
				get {
					return this.startTimeField;
				}
				set {
					this.startTimeField = value;
				}
			}
    
			/// <remarks/>
			public string Duration {
				get {
					return this.durationField;
				}
				set {
					this.durationField = value;
				}
			}
    
			/// <remarks/>
			public string Notes {
				get {
					return this.notesField;
				}
				set {
					this.notesField = value;
				}
			}
    
			/// <remarks/>
			public string Reason {
				get {
					return this.reasonField;
				}
				set {
					this.reasonField = value;
				}
			}
    
			/// <remarks/>
			public string SessionName {
				get {
					return this.sessionNameField;
				}
				set {
					this.sessionNameField = value;
				}
			}
    
			/// <remarks/>
			public int SessionDBID {
				get {
					return this.sessionDBIDField;
				}
				set {
					this.sessionDBIDField = value;
				}
			}
    
			/// <remarks/>
			[System.Xml.Serialization.XmlArrayItemAttribute("Holder", IsNullable=false)]
			public HolderStruct[] HolderList {
				get {
					return this.holderListField;
				}
				set {
					this.holderListField = value;
				}
			}
    
			/// <remarks/>
			public string Status {
				get {
					return this.statusField;
				}
				set {
					this.statusField = value;
				}
			}
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute("code")]
		[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.e-mis.com/emisopen/MedicalRecord")]
		public partial class HolderStruct {
    
			private int dBIDField;
    
			private int refIDField;
    
			private string titleField;
    
			private string firstNamesField;
    
			private string lastNameField;
    
			/// <remarks/>
			public int DBID {
				get {
					return this.dBIDField;
				}
				set {
					this.dBIDField = value;
				}
			}
    
			/// <remarks/>
			public int RefID {
				get {
					return this.refIDField;
				}
				set {
					this.refIDField = value;
				}
			}
    
			/// <remarks/>
			public string Title {
				get {
					return this.titleField;
				}
				set {
					this.titleField = value;
				}
			}
    
			/// <remarks/>
			public string FirstNames {
				get {
					return this.firstNamesField;
				}
				set {
					this.firstNamesField = value;
				}
			}
    
			/// <remarks/>
			public string LastName {
				get {
					return this.lastNameField;
				}
				set {
					this.lastNameField = value;
				}
			}
		}

}

