//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIS.PatientFlow.API.Data
{
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.e-mis.com/emisopen/MedicalRecord", IsNullable = false)]
    public partial class AppointmentSessionList
    {

        private AppointmentSessionStruct[] appointmentSessionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AppointmentSession")]
        public AppointmentSessionStruct[] AppointmentSession
        {
            get
            {
                return this.appointmentSessionField;
            }
            set
            {
                this.appointmentSessionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
    public partial class AppointmentSessionStruct
    {

        private int dBIDField;

        private string nameField;

        private string dateField;

        private string startTimeField;

        private string endTimeField;

        private string slotLengthField;

        private SlotsStruct[] slotTypeListField;

        private SiteStruct siteField;

        private HolderStruct[] holderListField;

        /// <remarks/>
        public int DBID
        {
            get
            {
                return this.dBIDField;
            }
            set
            {
                this.dBIDField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        public string StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        public string EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }

        /// <remarks/>
        public string SlotLength
        {
            get
            {
                return this.slotLengthField;
            }
            set
            {
                this.slotLengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SlotType", IsNullable = false)]
        public SlotsStruct[] SlotTypeList
        {
            get
            {
                return this.slotTypeListField;
            }
            set
            {
                this.slotTypeListField = value;
            }
        }

        /// <remarks/>
        public SiteStruct Site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Holder", IsNullable = false)]
        public HolderStruct[] HolderList
        {
            get
            {
                return this.holderListField;
            }
            set
            {
                this.holderListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
    public partial class SlotsStruct
    {

        private string typeIDField;

        private string descriptionField;

        private int totalField;

        private int bookedField;

        private int blockedField;

        private int embargoedField;

        private int availableField;

        /// <remarks/>
        public string TypeID
        {
            get
            {
                return this.typeIDField;
            }
            set
            {
                this.typeIDField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public int Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }

        /// <remarks/>
        public int Booked
        {
            get
            {
                return this.bookedField;
            }
            set
            {
                this.bookedField = value;
            }
        }

        /// <remarks/>
        public int Blocked
        {
            get
            {
                return this.blockedField;
            }
            set
            {
                this.blockedField = value;
            }
        }

        /// <remarks/>
        public int Embargoed
        {
            get
            {
                return this.embargoedField;
            }
            set
            {
                this.embargoedField = value;
            }
        }

        /// <remarks/>
        public int Available
        {
            get
            {
                return this.availableField;
            }
            set
            {
                this.availableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
    public partial class HolderStruct
    {

        private int dBIDField;

        private int refIDField;

        private string titleField;

        private string firstNamesField;

        private string lastNameField;

        /// <remarks/>
        public int DBID
        {
            get
            {
                return this.dBIDField;
            }
            set
            {
                this.dBIDField = value;
            }
        }

        /// <remarks/>
        public int RefID
        {
            get
            {
                return this.refIDField;
            }
            set
            {
                this.refIDField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string FirstNames
        {
            get
            {
                return this.firstNamesField;
            }
            set
            {
                this.firstNamesField = value;
            }
        }

        /// <remarks/>
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
    public partial class SiteStruct
    {

        private int dBIDField;

        private string nameField;

        /// <remarks/>
        public int DBID
        {
            get
            {
                return this.dBIDField;
            }
            set
            {
                this.dBIDField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
}