//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Slot
{

    private uint dBIDField;

    private uint refIDField;

    private System.DateTime startTimeField;

    private System.DateTime slotLengthField;

    private SlotType typeField;

    private string statusField;

    private SlotPatientList patientListField;

    private string notesField;

    private string reasonField;

    /// <remarks/>
    public uint DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public uint RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
    public System.DateTime StartTime
    {
        get
        {
            return this.startTimeField;
        }
        set
        {
            this.startTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
    public System.DateTime SlotLength
    {
        get
        {
            return this.slotLengthField;
        }
        set
        {
            this.slotLengthField = value;
        }
    }

    /// <remarks/>
    public SlotType Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public string Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    public SlotPatientList PatientList
    {
        get
        {
            return this.patientListField;
        }
        set
        {
            this.patientListField = value;
        }
    }

    /// <remarks/>
    public string Notes
    {
        get
        {
            return this.notesField;
        }
        set
        {
            this.notesField = value;
        }
    }

    /// <remarks/>
    public string Reason
    {
        get
        {
            return this.reasonField;
        }
        set
        {
            this.reasonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SlotType
{

    private string descriptionField;

    private string typeIDField;

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public string TypeID
    {
        get
        {
            return this.typeIDField;
        }
        set
        {
            this.typeIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SlotPatientList
{

    private SlotPatientListPatient patientField;

    /// <remarks/>
    public SlotPatientListPatient Patient
    {
        get
        {
            return this.patientField;
        }
        set
        {
            this.patientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class SlotPatientListPatient
{

    private uint dBIDField;

    private uint refIDField;

    private string titleField;

    private string firstNamesField;

    private string surnameField;

    private string fullNameField;

    /// <remarks/>
    public uint DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public uint RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    public string FirstNames
    {
        get
        {
            return this.firstNamesField;
        }
        set
        {
            this.firstNamesField = value;
        }
    }

    /// <remarks/>
    public string Surname
    {
        get
        {
            return this.surnameField;
        }
        set
        {
            this.surnameField = value;
        }
    }

    /// <remarks/>
    public string FullName
    {
        get
        {
            return this.fullNameField;
        }
        set
        {
            this.fullNameField = value;
        }
    }
}
