//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIS.PatientFlow.API.Data
{
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.e-mis.com/emisopen/MedicalRecord", IsNullable = false)]
    public partial class BookedPatients
    {

        private BookedPatientsBooked[] bookedListField;

        private BookedPatientsSessionHolder[] sessionHolderListField;

        private string timeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Booked", IsNullable = false)]
        public BookedPatientsBooked[] BookedList
        {
            get
            {
                return this.bookedListField;
            }
            set
            {
                this.bookedListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SessionHolder", IsNullable = false)]
        public BookedPatientsSessionHolder[] SessionHolderList
        {
            get
            {
                return this.sessionHolderListField;
            }
            set
            {
                this.sessionHolderListField = value;
            }
        }

        /// <remarks/>
        public string Time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
    public partial class BookedPatientsBooked
    {

        private RegistrationType patientField;

        private BookedPatientsBookedAppointment appointmentField;

        private BookedPatientsBookedAlert alertField;

        private bool alertFieldSpecified;

        /// <remarks/>
        public RegistrationType Patient
        {
            get
            {
                return this.patientField;
            }
            set
            {
                this.patientField = value;
            }
        }

        /// <remarks/>
        public BookedPatientsBookedAppointment Appointment
        {
            get
            {
                return this.appointmentField;
            }
            set
            {
                this.appointmentField = value;
            }
        }

        /// <remarks/>
        public BookedPatientsBookedAlert Alert
        {
            get
            {
                return this.alertField;
            }
            set
            {
                this.alertField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlertSpecified
        {
            get
            {
                return this.alertFieldSpecified;
            }
            set
            {
                this.alertFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
    public partial class BookedPatientsBookedAppointment
    {

        private IdentType idField;

        private string appointmentSiteField;

        private string appointmentNameField;

        private string dateField;

        private string timeField;

        private IdentType sessionHolderField;

        private IdentType[] sessionUsersListField;

        private IdentType[] sessionLocationsListField;

        private long sessionIdField;

        /// <remarks/>
        public IdentType ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string AppointmentSite
        {
            get
            {
                return this.appointmentSiteField;
            }
            set
            {
                this.appointmentSiteField = value;
            }
        }

        /// <remarks/>
        public string AppointmentName
        {
            get
            {
                return this.appointmentNameField;
            }
            set
            {
                this.appointmentNameField = value;
            }
        }

        /// <remarks/>
        public string Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        public string Time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        public IdentType SessionHolder
        {
            get
            {
                return this.sessionHolderField;
            }
            set
            {
                this.sessionHolderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SessionUser", IsNullable = false)]
        public IdentType[] SessionUsersList
        {
            get
            {
                return this.sessionUsersListField;
            }
            set
            {
                this.sessionUsersListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SessionLocation", IsNullable = false)]
        public IdentType[] SessionLocationsList
        {
            get
            {
                return this.sessionLocationsListField;
            }
            set
            {
                this.sessionLocationsListField = value;
            }
        }

        /// <remarks/>
        public long SessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
    public enum BookedPatientsBookedAlert
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
    public partial class BookedPatientsSessionHolder : PersonType
    {

        private string waitingTimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string WaitingTime
        {
            get
            {
                return this.waitingTimeField;
            }
            set
            {
                this.waitingTimeField = value;
            }
        }
    }

}
