//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.e-mis.com/emisopen/MedicalRecord", IsNullable = false)]
public partial class MedicalRecord
{

    private MedicalRecordConsultationList consultationListField;

    private MedicalRecordPerson peopleListField;

    private MedicalRecordLocationList locationListField;

    private MedicalRecordLocationTypeList locationTypeListField;

    private int patientIDField;

    /// <remarks/>
    public MedicalRecordConsultationList ConsultationList
    {
        get
        {
            return this.consultationListField;
        }
        set
        {
            this.consultationListField = value;
        }
    }

    ///// <remarks/>
    //public MedicalRecordPeopleList PeopleList {
    //    get {
    //        return this.peopleListField;
    //    }
    //    set {
    //        this.peopleListField = value;
    //    }
    //}

    /// <remarks/>
    public MedicalRecordPerson PeopleList
    {
        get
        {
            return this.peopleListField;
        }
        set
        {
            this.peopleListField = value;
        }
    }

    /// <remarks/>
    public MedicalRecordLocationList LocationList
    {
        get
        {
            return this.locationListField;
        }
        set
        {
            this.locationListField = value;
        }
    }

    /// <remarks/>
    public MedicalRecordLocationTypeList LocationTypeList
    {
        get
        {
            return this.locationTypeListField;
        }
        set
        {
            this.locationTypeListField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int PatientID
    {
        get
        {
            return this.patientIDField;
        }
        set
        {
            this.patientIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationList
{

    private MedicalRecordConsultationListConsultation consultationField;

    /// <remarks/>
    public MedicalRecordConsultationListConsultation Consultation
    {
        get
        {
            return this.consultationField;
        }
        set
        {
            this.consultationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultation
{

    private string gUIDField;

    private string assignedDateField;

    private MedicalRecordConsultationListConsultationUserID userIDField;

    private MedicalRecordConsultationListConsultationLocationID locationIDField;

    private MedicalRecordConsultationListConsultationLocationTypeID locationTypeIDField;

    private MedicalRecordConsultationListConsultationOriginalAuthor originalAuthorField;

    private MedicalRecordConsultationListConsultationElementList elementListField;

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public string AssignedDate
    {
        get
        {
            return this.assignedDateField;
        }
        set
        {
            this.assignedDateField = value;
        }
    }

    /// <remarks/>
    public MedicalRecordConsultationListConsultationUserID UserID
    {
        get
        {
            return this.userIDField;
        }
        set
        {
            this.userIDField = value;
        }
    }

    /// <remarks/>
    public MedicalRecordConsultationListConsultationLocationID LocationID
    {
        get
        {
            return this.locationIDField;
        }
        set
        {
            this.locationIDField = value;
        }
    }

    /// <remarks/>
    public MedicalRecordConsultationListConsultationLocationTypeID LocationTypeID
    {
        get
        {
            return this.locationTypeIDField;
        }
        set
        {
            this.locationTypeIDField = value;
        }
    }

    /// <remarks/>
    public MedicalRecordConsultationListConsultationOriginalAuthor OriginalAuthor
    {
        get
        {
            return this.originalAuthorField;
        }
        set
        {
            this.originalAuthorField = value;
        }
    }

    public MedicalRecordConsultationListConsultationElementList ElementList
    {
        get
        {
            return this.elementListField;
        }
        set
        {
            this.elementListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationUserID
{

    private int refIDField;

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationLocationID
{

    private int refIDField;

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationLocationTypeID
{

    private int refIDField;

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationOriginalAuthor
{

    private MedicalRecordConsultationListConsultationOriginalAuthorUser userField;

    /// <remarks/>
    public MedicalRecordConsultationListConsultationOriginalAuthorUser User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationOriginalAuthorUser
{

    private int refIDField;

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementList
{

    private MedicalRecordConsultationListConsultationElementListConsultationElement[] consultationElementField;

    [System.Xml.Serialization.XmlElementAttribute("ConsultationElement")]
    public MedicalRecordConsultationListConsultationElementListConsultationElement[] ConsultationElement
    {
        get
        {
            return this.consultationElementField;
        }
        set
        {
            this.consultationElementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementListConsultationElement
{

    private int refIDField;

    private string gUIDField;

    private int fileStatusField;

    private int displayOrderField;

    private int problemSectionField;

    private MedicalRecordConsultationListConsultationElementListConsultationElementHeader headerField;

    private MedicalRecordConsultationListConsultationElementListConsultationElementAttachment attachmentField;

    private MedicalRecordConsultationListConsultationElementListConsultationElementEvent eventField;

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public int FileStatus
    {
        get
        {
            return this.fileStatusField;
        }
        set
        {
            this.fileStatusField = value;
        }
    }

    /// <remarks/>
    public int DisplayOrder
    {
        get
        {
            return this.displayOrderField;
        }
        set
        {
            this.displayOrderField = value;
        }
    }

    /// <remarks/>
    public int ProblemSection
    {
        get
        {
            return this.problemSectionField;
        }
        set
        {
            this.problemSectionField = value;
        }
    }

    /// <remarks/>
    public MedicalRecordConsultationListConsultationElementListConsultationElementHeader Header
    {
        get
        {
            return this.headerField;
        }
        set
        {
            this.headerField = value;
        }
    }

    /// <remarks/>
    public MedicalRecordConsultationListConsultationElementListConsultationElementAttachment Attachment
    {
        get
        {
            return this.attachmentField;
        }
        set
        {
            this.attachmentField = value;
        }
    }

    public MedicalRecordConsultationListConsultationElementListConsultationElementEvent Event
    {
        get
        {
            return this.eventField;
        }
        set
        {
            this.eventField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementListConsultationElementHeader
{

    private int valueField;

    private int schemeField;

    private string termField;

    /// <remarks/>
    public int Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    public int Scheme
    {
        get
        {
            return this.schemeField;
        }
        set
        {
            this.schemeField = value;
        }
    }

    /// <remarks/>
    public string Term
    {
        get
        {
            return this.termField;
        }
        set
        {
            this.termField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementListConsultationElementEvent
{
    private int refIDField;

    private int DBIDField;

    private string gUIDField;

    private string assignedDateField;

    private MedicalRecordConsultationListConsultationElementListConsultationElementEventAuthorID authorIDField;

    private MedicalRecordConsultationListConsultationElementListConsultationElementEventOriginalAuthor originalAuthorField;

    private string displayTermField;

    private MedicalRecordConsultationListConsultationElementListConsultationElementEventCode codeField;

    private MedicalRecordConsultationListConsultationElementListConsultationElementEventTerm termField;

    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    public int DBID
    {
        get
        {
            return this.DBIDField;
        }
        set
        {
            this.DBIDField = value;
        }
    }

    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    public string AssignedDate
    {
        get
        {
            return this.assignedDateField;
        }
        set
        {
            this.assignedDateField = value;
        }
    }

    public MedicalRecordConsultationListConsultationElementListConsultationElementEventAuthorID AuthorID
    {
        get
        {
            return this.authorIDField;
        }
        set
        {
            this.authorIDField = value;
        }
    }

    public MedicalRecordConsultationListConsultationElementListConsultationElementEventOriginalAuthor OriginalAuthor
    {
        get
        {
            return this.originalAuthorField;
        }
        set
        {
            this.originalAuthorField = value;
        }
    }

    public string DisplayTerm
    {
        get
        {
            return this.displayTermField;
        }
        set
        {
            this.displayTermField = value;
        }
    }

    public MedicalRecordConsultationListConsultationElementListConsultationElementEventCode Code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    public MedicalRecordConsultationListConsultationElementListConsultationElementEventTerm TermID
    {
        get
        {
            return this.termField;
        }
        set
        {
            this.termField = value;
        }
    }

}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementListConsultationElementAttachment
{

    private int refIDField;

    private string gUIDField;

    private string assignedDateField;

    private MedicalRecordConsultationListConsultationElementListConsultationElementAttachmentAuthorID authorIDField;

    private MedicalRecordConsultationListConsultationElementListConsultationElementAttachmentOriginalAuthor originalAuthorField;

    private string descriptiveTextField;

    private string addressField;

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public string AssignedDate
    {
        get
        {
            return this.assignedDateField;
        }
        set
        {
            this.assignedDateField = value;
        }
    }

    /// <remarks/>
    public MedicalRecordConsultationListConsultationElementListConsultationElementAttachmentAuthorID AuthorID
    {
        get
        {
            return this.authorIDField;
        }
        set
        {
            this.authorIDField = value;
        }
    }

    /// <remarks/>
    public MedicalRecordConsultationListConsultationElementListConsultationElementAttachmentOriginalAuthor OriginalAuthor
    {
        get
        {
            return this.originalAuthorField;
        }
        set
        {
            this.originalAuthorField = value;
        }
    }

    /// <remarks/>
    public string DescriptiveText
    {
        get
        {
            return this.descriptiveTextField;
        }
        set
        {
            this.descriptiveTextField = value;
        }
    }

    /// <remarks/>
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementListConsultationElementAttachmentAuthorID
{

    private int refIDField;

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }
}

// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementListConsultationElementEventCode
{

    private string valueField;

    private string schemeField;

    private string termField;

    /// <remarks/>
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    public string Scheme
    {
        get
        {
            return this.schemeField;
        }
        set
        {
            this.schemeField = value;
        }
    }

    public string Term
    {
        get
        {
            return this.termField;
        }
        set
        {
            this.termField = value;
        }
    }
}

// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementListConsultationElementEventTerm
{

    private string valueField;

    private string schemeField;

    private string termField;

    /// <remarks/>
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    public string Scheme
    {
        get
        {
            return this.schemeField;
        }
        set
        {
            this.schemeField = value;
        }
    }

    public string Term
    {
        get
        {
            return this.termField;
        }
        set
        {
            this.termField = value;
        }
    }
}

// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementListConsultationElementEventAuthorID
{

    private int refIDField;

    private int DBIDField;

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    public int DBID
    {
        get
        {
            return this.DBIDField;
        }
        set
        {
            this.DBIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementListConsultationElementAttachmentOriginalAuthor
{

    private MedicalRecordConsultationListConsultationElementListConsultationElementAttachmentOriginalAuthorUser userField;

    /// <remarks/>
    public MedicalRecordConsultationListConsultationElementListConsultationElementAttachmentOriginalAuthorUser User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementListConsultationElementEventOriginalAuthor
{
    private MedicalRecordConsultationListConsultationElementListConsultationElementEventOriginalAuthorUser userField;

    private string systemDateField;

    /// <remarks/>
    public MedicalRecordConsultationListConsultationElementListConsultationElementEventOriginalAuthorUser User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }

    public string SystemDate
    {
        get
        {
            return this.systemDateField;
        }
        set
        {
            this.systemDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementListConsultationElementAttachmentOriginalAuthorUser
{

    private int refIDField;

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordConsultationListConsultationElementListConsultationElementEventOriginalAuthorUser
{

    private int refIDField;

    private int DBIDField;

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    public int DBID
    {
        get
        {
            return this.DBIDField;
        }
        set
        {
            this.DBIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordPerson
{

    private MedicalRecordPeopleListPerson[] personField;

    [System.Xml.Serialization.XmlElementAttribute("Person")]
    public MedicalRecordPeopleListPerson[] Person
    {
        get
        {
            return this.personField;
        }
        set
        {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordPeopleListPerson
{

    private int dBIDField;

    private int refIDField;

    private string gUIDField;

    private string titleField;

    private string firstNamesField;

    private string lastNameField;

    /// <remarks/>
    public int DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    public string FirstNames
    {
        get
        {
            return this.firstNamesField;
        }
        set
        {
            this.firstNamesField = value;
        }
    }

    /// <remarks/>
    public string LastName
    {
        get
        {
            return this.lastNameField;
        }
        set
        {
            this.lastNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordLocationList
{

    private MedicalRecordLocationListLocation locationField;

    /// <remarks/>
    public MedicalRecordLocationListLocation Location
    {
        get
        {
            return this.locationField;
        }
        set
        {
            this.locationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordLocationListLocation
{

    private int dBIDField;

    private int refIDField;

    private string gUIDField;

    private int fileStatusField;

    private string locationNameField;

    private MedicalRecordLocationListLocationLocationTypeID locationTypeIDField;

    /// <remarks/>
    public int DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public int FileStatus
    {
        get
        {
            return this.fileStatusField;
        }
        set
        {
            this.fileStatusField = value;
        }
    }

    /// <remarks/>
    public string LocationName
    {
        get
        {
            return this.locationNameField;
        }
        set
        {
            this.locationNameField = value;
        }
    }

    /// <remarks/>
    public MedicalRecordLocationListLocationLocationTypeID LocationTypeID
    {
        get
        {
            return this.locationTypeIDField;
        }
        set
        {
            this.locationTypeIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordLocationListLocationLocationTypeID
{

    private int refIDField;

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordLocationTypeList
{

    private MedicalRecordLocationTypeListLocationType locationTypeField;

    /// <remarks/>
    public MedicalRecordLocationTypeListLocationType LocationType
    {
        get
        {
            return this.locationTypeField;
        }
        set
        {
            this.locationTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class MedicalRecordLocationTypeListLocationType
{

    private int dBIDField;

    private int refIDField;

    private int fileStatusField;

    private string descriptionField;

    /// <remarks/>
    public int DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public int RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public int FileStatus
    {
        get
        {
            return this.fileStatusField;
        }
        set
        {
            this.fileStatusField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}
