//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.e-mis.com/emisopen/MedicalRecord", IsNullable = false)]
public partial class OrganisationInformation
{

    private OrganisationInformationOrganisationList organisationListField;

    private OrganisationInformationUser[] userListField;

    private OrganisationInformationExternalOrganisationList externalOrganisationListField;

    private object externalPersonListField;

    private OrganisationInformationLocationType[] locationTypeListField;

    /// <remarks/>
    public OrganisationInformationOrganisationList OrganisationList
    {
        get
        {
            return this.organisationListField;
        }
        set
        {
            this.organisationListField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("User", IsNullable = false)]
    public OrganisationInformationUser[] UserList
    {
        get
        {
            return this.userListField;
        }
        set
        {
            this.userListField = value;
        }
    }

    /// <remarks/>
    public OrganisationInformationExternalOrganisationList ExternalOrganisationList
    {
        get
        {
            return this.externalOrganisationListField;
        }
        set
        {
            this.externalOrganisationListField = value;
        }
    }

    /// <remarks/>
    public object ExternalPersonList
    {
        get
        {
            return this.externalPersonListField;
        }
        set
        {
            this.externalPersonListField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LocationType", IsNullable = false)]
    public OrganisationInformationLocationType[] LocationTypeList
    {
        get
        {
            return this.locationTypeListField;
        }
        set
        {
            this.locationTypeListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationOrganisationList
{

    private OrganisationInformationOrganisationListOrganisation organisationField;

    /// <remarks/>
    public OrganisationInformationOrganisationListOrganisation Organisation
    {
        get
        {
            return this.organisationField;
        }
        set
        {
            this.organisationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationOrganisationListOrganisation
{

    private uint dBIDField;

    private uint refIDField;

    private string gUIDField;

    private string locationNameField;

    private string nationalCodeField;

    private OrganisationInformationOrganisationListOrganisationLocationTypeID locationTypeIDField;

    private OrganisationInformationOrganisationListOrganisationAddress addressField;

    private string telephone1Field;

    private object faxField;

    private object contactField;

    /// <remarks/>
    public uint DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public uint RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public string LocationName
    {
        get
        {
            return this.locationNameField;
        }
        set
        {
            this.locationNameField = value;
        }
    }

    /// <remarks/>
    public string NationalCode
    {
        get
        {
            return this.nationalCodeField;
        }
        set
        {
            this.nationalCodeField = value;
        }
    }

    /// <remarks/>
    public OrganisationInformationOrganisationListOrganisationLocationTypeID LocationTypeID
    {
        get
        {
            return this.locationTypeIDField;
        }
        set
        {
            this.locationTypeIDField = value;
        }
    }

    /// <remarks/>
    public OrganisationInformationOrganisationListOrganisationAddress Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    public string Telephone1
    {
        get
        {
            return this.telephone1Field;
        }
        set
        {
            this.telephone1Field = value;
        }
    }

    /// <remarks/>
    public object Fax
    {
        get
        {
            return this.faxField;
        }
        set
        {
            this.faxField = value;
        }
    }

    /// <remarks/>
    public object Contact
    {
        get
        {
            return this.contactField;
        }
        set
        {
            this.contactField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationOrganisationListOrganisationLocationTypeID
{

    private byte dBIDField;

    private byte refIDField;

    private string gUIDField;

    /// <remarks/>
    public byte DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public byte RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationOrganisationListOrganisationAddress
{

    private uint dBIDField;

    private string gUIDField;

    private string houseNameFlatField;

    private string streetField;

    private string villageField;

    private string townField;

    private string countyField;

    private string postCodeField;

    /// <remarks/>
    public uint DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public string HouseNameFlat
    {
        get
        {
            return this.houseNameFlatField;
        }
        set
        {
            this.houseNameFlatField = value;
        }
    }

    /// <remarks/>
    public string Street
    {
        get
        {
            return this.streetField;
        }
        set
        {
            this.streetField = value;
        }
    }

    /// <remarks/>
    public string Village
    {
        get
        {
            return this.villageField;
        }
        set
        {
            this.villageField = value;
        }
    }

    /// <remarks/>
    public string Town
    {
        get
        {
            return this.townField;
        }
        set
        {
            this.townField = value;
        }
    }

    /// <remarks/>
    public string County
    {
        get
        {
            return this.countyField;
        }
        set
        {
            this.countyField = value;
        }
    }

    /// <remarks/>
    public string PostCode
    {
        get
        {
            return this.postCodeField;
        }
        set
        {
            this.postCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationUser
{

    private uint dBIDField;

    private uint refIDField;

    private string gUIDField;

    private string mnemonicField;

    private uint pCSUserField;

    private string activeEMISUserField;

    private string titleField;

    private string firstNamesField;

    private string lastNameField;

    private OrganisationInformationUserCategory categoryField;

    private string nationalCodeField;

    private string scriptsField;

    private string consulterField;

    private string contractStartField;

    private OrganisationInformationUserRole roleField;

    private string security1Field;

    /// <remarks/>
    public uint DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public uint RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public string Mnemonic
    {
        get
        {
            return this.mnemonicField;
        }
        set
        {
            this.mnemonicField = value;
        }
    }

    /// <remarks/>
    public uint PCSUser
    {
        get
        {
            return this.pCSUserField;
        }
        set
        {
            this.pCSUserField = value;
        }
    }

    /// <remarks/>
    public string ActiveEMISUser
    {
        get
        {
            return this.activeEMISUserField;
        }
        set
        {
            this.activeEMISUserField = value;
        }
    }

    /// <remarks/>
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    public string FirstNames
    {
        get
        {
            return this.firstNamesField;
        }
        set
        {
            this.firstNamesField = value;
        }
    }

    /// <remarks/>
    public string LastName
    {
        get
        {
            return this.lastNameField;
        }
        set
        {
            this.lastNameField = value;
        }
    }

    /// <remarks/>
    public OrganisationInformationUserCategory Category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }

    /// <remarks/>
    public string NationalCode
    {
        get
        {
            return this.nationalCodeField;
        }
        set
        {
            this.nationalCodeField = value;
        }
    }

    /// <remarks/>
    public string Scripts
    {
        get
        {
            return this.scriptsField;
        }
        set
        {
            this.scriptsField = value;
        }
    }

    /// <remarks/>
    public string Consulter
    {
        get
        {
            return this.consulterField;
        }
        set
        {
            this.consulterField = value;
        }
    }

    /// <remarks/>
    public string ContractStart
    {
        get
        {
            return this.contractStartField;
        }
        set
        {
            this.contractStartField = value;
        }
    }

    /// <remarks/>
    public OrganisationInformationUserRole Role
    {
        get
        {
            return this.roleField;
        }
        set
        {
            this.roleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Security1
    {
        get
        {
            return this.security1Field;
        }
        set
        {
            this.security1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationUserCategory
{

    private uint dBIDField;

    private uint refIDField;

    private string descriptionField;

    /// <remarks/>
    public uint DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public uint RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationUserRole
{

    private byte dBIDField;

    private byte refIDField;

    private OrganisationInformationUserRoleLocation locationField;

    /// <remarks/>
    public byte DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public byte RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public OrganisationInformationUserRoleLocation Location
    {
        get
        {
            return this.locationField;
        }
        set
        {
            this.locationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationUserRoleLocation
{

    private uint dBIDField;

    private uint refIDField;

    /// <remarks/>
    public uint DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public uint RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationExternalOrganisationList
{

    private OrganisationInformationExternalOrganisationListOrganisation organisationField;

    /// <remarks/>
    public OrganisationInformationExternalOrganisationListOrganisation Organisation
    {
        get
        {
            return this.organisationField;
        }
        set
        {
            this.organisationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationExternalOrganisationListOrganisation
{

    private uint dBIDField;

    private uint refIDField;

    private string gUIDField;

    private byte fileStatusField;

    private string locationNameField;

    private string nationalCodeField;

    private OrganisationInformationExternalOrganisationListOrganisationLocationTypeID locationTypeIDField;

    private OrganisationInformationExternalOrganisationListOrganisationAddress addressField;

    private string telephone1Field;

    private object faxField;

    private object emailField;

    /// <remarks/>
    public uint DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public uint RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public byte FileStatus
    {
        get
        {
            return this.fileStatusField;
        }
        set
        {
            this.fileStatusField = value;
        }
    }

    /// <remarks/>
    public string LocationName
    {
        get
        {
            return this.locationNameField;
        }
        set
        {
            this.locationNameField = value;
        }
    }

    /// <remarks/>
    public string NationalCode
    {
        get
        {
            return this.nationalCodeField;
        }
        set
        {
            this.nationalCodeField = value;
        }
    }

    /// <remarks/>
    public OrganisationInformationExternalOrganisationListOrganisationLocationTypeID LocationTypeID
    {
        get
        {
            return this.locationTypeIDField;
        }
        set
        {
            this.locationTypeIDField = value;
        }
    }

    /// <remarks/>
    public OrganisationInformationExternalOrganisationListOrganisationAddress Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    public string Telephone1
    {
        get
        {
            return this.telephone1Field;
        }
        set
        {
            this.telephone1Field = value;
        }
    }

    /// <remarks/>
    public object Fax
    {
        get
        {
            return this.faxField;
        }
        set
        {
            this.faxField = value;
        }
    }

    /// <remarks/>
    public object Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationExternalOrganisationListOrganisationLocationTypeID
{

    private byte dBIDField;

    private byte refIDField;

    private string gUIDField;

    private byte fileStatusField;

    /// <remarks/>
    public byte DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public byte RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public byte FileStatus
    {
        get
        {
            return this.fileStatusField;
        }
        set
        {
            this.fileStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationExternalOrganisationListOrganisationAddress
{

    private uint dBIDField;

    private string gUIDField;

    private string houseNameFlatField;

    private string streetField;

    private object villageField;

    private string townField;

    private string countyField;

    private string postCodeField;

    /// <remarks/>
    public uint DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public string HouseNameFlat
    {
        get
        {
            return this.houseNameFlatField;
        }
        set
        {
            this.houseNameFlatField = value;
        }
    }

    /// <remarks/>
    public string Street
    {
        get
        {
            return this.streetField;
        }
        set
        {
            this.streetField = value;
        }
    }

    /// <remarks/>
    public object Village
    {
        get
        {
            return this.villageField;
        }
        set
        {
            this.villageField = value;
        }
    }

    /// <remarks/>
    public string Town
    {
        get
        {
            return this.townField;
        }
        set
        {
            this.townField = value;
        }
    }

    /// <remarks/>
    public string County
    {
        get
        {
            return this.countyField;
        }
        set
        {
            this.countyField = value;
        }
    }

    /// <remarks/>
    public string PostCode
    {
        get
        {
            return this.postCodeField;
        }
        set
        {
            this.postCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class OrganisationInformationLocationType
{

    private ulong dBIDField;

    private ulong refIDField;

    private string gUIDField;

    private string descriptionField;

    /// <remarks/>
    public ulong DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public ulong RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}
