//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace EMIS.PatientFlow.API.Data
{
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.e-mis.com/emisopen/MedicalRecord", IsNullable = false)]
    public partial class PatientMatches
    {

        private PatientMatchesPatient[] patientListField;

        private PersonType[] peopleListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Patient", IsNullable = false)]
        public PatientMatchesPatient[] PatientList
        {
            get
            {
                return this.patientListField;
            }
            set
            {
                this.patientListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Person", IsNullable = false)]
        public PersonType[] PeopleList
        {
            get
            {
                return this.peopleListField;
            }
            set
            {
                this.peopleListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
    public partial class PatientMatchesPatient : RegistrationType
    {

        private StatusType currentStatusField;

        /// <remarks/>
        public StatusType CurrentStatus
        {
            get
            {
                return this.currentStatusField;
            }
            set
            {
                this.currentStatusField = value;
            }
        }

		public string PatientDisplayName
		{
			get
			{
				return string.IsNullOrEmpty(Title) ?
				   string.Format("{0} {1}", FirstNames, FamilyName) :
				   string.Format("{0}. {1} {2}", Title, FirstNames, FamilyName);
			}
		}

	}

}