using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EMIS.PatientFlow.API.Data
{
	public class PCSPatientsAppointmentList
	{
		// 
		// This source code was auto-generated by xsd, Version=4.0.30319.17929.
		// 

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute("code")]
		[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
		[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
		public partial class PatientAppointmentList
		{
			private AppointmentStruct[] appointmentField;

			/// <remarks/>
			[System.Xml.Serialization.XmlElementAttribute("Appointment", IsNullable = false)]
			public AppointmentStruct[] Appointment
			{
				get
				{
					return this.appointmentField;
				}
				set
				{
					this.appointmentField = value;
				}
			}
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute("code")]
		[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
		public partial class AppointmentStruct
		{

			private int slotIDField;

			private int siteIDField;

			private string dateField;

			private string startTimeField;

			private string durationField;

			private string notesField;

			private string reasonField;

			private string sessionNameField;

			private int sessionDBIDField;

			private HolderStruct[] holderListField;

			private string statusField;

			/// <remarks/>
			public int SlotID
			{
				get
				{
					return this.slotIDField;
				}
				set
				{
					this.slotIDField = value;
				}
			}

			/// <remarks/>
			public int SiteID
			{
				get
				{
					return this.siteIDField;
				}
				set
				{
					this.siteIDField = value;
				}
			}

			/// <remarks/>
			public string Date
			{
				get
				{
					return this.dateField;
				}
				set
				{
					this.dateField = value;
				}
			}

			/// <remarks/>
			public string StartTime
			{
				get
				{
					return this.startTimeField;
				}
				set
				{
					this.startTimeField = value;
				}
			}

			/// <remarks/>
			public string Duration
			{
				get
				{
					return this.durationField;
				}
				set
				{
					this.durationField = value;
				}
			}

			/// <remarks/>
			public string Notes
			{
				get
				{
					return this.notesField;
				}
				set
				{
					this.notesField = value;
				}
			}

			/// <remarks/>
			public string Reason
			{
				get
				{
					return this.reasonField;
				}
				set
				{
					this.reasonField = value;
				}
			}

			/// <remarks/>
			public string SessionName
			{
				get
				{
					return this.sessionNameField;
				}
				set
				{
					this.sessionNameField = value;
				}
			}

			/// <remarks/>
			public int SessionDBID
			{
				get
				{
					return this.sessionDBIDField;
				}
				set
				{
					this.sessionDBIDField = value;
				}
			}

			/// <remarks/>
			[System.Xml.Serialization.XmlArrayItemAttribute("Holder", IsNullable = false)]
			public HolderStruct[] HolderList
			{
				get
				{
					return this.holderListField;
				}
				set
				{
					this.holderListField = value;
				}
			}

			/// <remarks/>
			public string Status
			{
				get
				{
					return this.statusField;
				}
				set
				{
					this.statusField = value;
				}
			}
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute("code")]
		[System.Xml.Serialization.XmlTypeAttribute(Namespace = "")]
		public partial class HolderStruct
		{
			private int dBIDField;

			private int refIDField;

			private string titleField;

			private string firstNamesField;

			private string lastNameField;

			/// <remarks/>
			public int DBID
			{
				get
				{
					return this.dBIDField;
				}
				set
				{
					this.dBIDField = value;
				}
			}

			/// <remarks/>
			public int RefID
			{
				get
				{
					return this.refIDField;
				}
				set
				{
					this.refIDField = value;
				}
			}

			/// <remarks/>
			public string Title
			{
				get
				{
					return this.titleField;
				}
				set
				{
					this.titleField = value;
				}
			}

			/// <remarks/>
			public string FirstNames
			{
				get
				{
					return this.firstNamesField;
				}
				set
				{
					this.firstNamesField = value;
				}
			}

			/// <remarks/>
			public string LastName
			{
				get
				{
					return this.lastNameField;
				}
				set
				{
					this.lastNameField = value;
				}
			}
		}
	}
}
