//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.e-mis.com/emisopen/MedicalRecord", IsNullable = false)]
public partial class UserDetails
{

    private UserDetailsPerson personField;

    /// <remarks/>
    public UserDetailsPerson Person
    {
        get
        {
            return this.personField;
        }
        set
        {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class UserDetailsPerson
{

    private ushort dBIDField;

    private ushort refIDField;

    private string gUIDField;

    private string mnemonicField;

    private ushort pCSUserField;

    private string activeEMISUserField;

    private string titleField;

    private string firstNamesField;

    private string lastNameField;

    private UserDetailsPersonCategory categoryField;

    private string nationalCodeField;

    private uint prescriptionCodeField;

    private uint gmcCodeField;

    private string scriptsField;

    private string consulterField;

    private string contractStartField;

    private object emailField;

    private UserDetailsPersonRole roleField;

    private string security1Field;

    /// <remarks/>
    public ushort DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public ushort RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }

    /// <remarks/>
    public string Mnemonic
    {
        get
        {
            return this.mnemonicField;
        }
        set
        {
            this.mnemonicField = value;
        }
    }

    /// <remarks/>
    public ushort PCSUser
    {
        get
        {
            return this.pCSUserField;
        }
        set
        {
            this.pCSUserField = value;
        }
    }

    /// <remarks/>
    public string ActiveEMISUser
    {
        get
        {
            return this.activeEMISUserField;
        }
        set
        {
            this.activeEMISUserField = value;
        }
    }

    /// <remarks/>
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    public string FirstNames
    {
        get
        {
            return this.firstNamesField;
        }
        set
        {
            this.firstNamesField = value;
        }
    }

    /// <remarks/>
    public string LastName
    {
        get
        {
            return this.lastNameField;
        }
        set
        {
            this.lastNameField = value;
        }
    }

    /// <remarks/>
    public UserDetailsPersonCategory Category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }

    /// <remarks/>
    public string NationalCode
    {
        get
        {
            return this.nationalCodeField;
        }
        set
        {
            this.nationalCodeField = value;
        }
    }

    /// <remarks/>
    public uint PrescriptionCode
    {
        get
        {
            return this.prescriptionCodeField;
        }
        set
        {
            this.prescriptionCodeField = value;
        }
    }

    /// <remarks/>
    public uint GmcCode
    {
        get
        {
            return this.gmcCodeField;
        }
        set
        {
            this.gmcCodeField = value;
        }
    }

    /// <remarks/>
    public string Scripts
    {
        get
        {
            return this.scriptsField;
        }
        set
        {
            this.scriptsField = value;
        }
    }

    /// <remarks/>
    public string Consulter
    {
        get
        {
            return this.consulterField;
        }
        set
        {
            this.consulterField = value;
        }
    }

    /// <remarks/>
    public string ContractStart
    {
        get
        {
            return this.contractStartField;
        }
        set
        {
            this.contractStartField = value;
        }
    }

    /// <remarks/>
    public object Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }

    /// <remarks/>
    public UserDetailsPersonRole Role
    {
        get
        {
            return this.roleField;
        }
        set
        {
            this.roleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Security1
    {
        get
        {
            return this.security1Field;
        }
        set
        {
            this.security1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class UserDetailsPersonCategory
{

    private ushort dBIDField;

    private ushort refIDField;

    private string descriptionField;

    /// <remarks/>
    public ushort DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public ushort RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class UserDetailsPersonRole
{

    private ushort dBIDField;

    private ushort refIDField;

    private object applicationField;

    private UserDetailsPersonRoleLocation locationField;

    /// <remarks/>
    public ushort DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
    public ushort RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }

    /// <remarks/>
    public object Application
    {
        get
        {
            return this.applicationField;
        }
        set
        {
            this.applicationField = value;
        }
    }

    /// <remarks/>
    public UserDetailsPersonRoleLocation Location
    {
        get
        {
            return this.locationField;
        }
        set
        {
            this.locationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.e-mis.com/emisopen/MedicalRecord")]
public partial class UserDetailsPersonRoleLocation
{

    private double dBIDField;

	private double refIDField;

    /// <remarks/>
	public double DBID
    {
        get
        {
            return this.dBIDField;
        }
        set
        {
            this.dBIDField = value;
        }
    }

    /// <remarks/>
	public double RefID
    {
        get
        {
            return this.refIDField;
        }
        set
        {
            this.refIDField = value;
        }
    }
}
