//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
public partial class AppointmentSessions
{
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AppointmentSessionList
    {

        private AppointmentSessionListAppointmentSession[] appointmentSessionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AppointmentSession")]
        public AppointmentSessionListAppointmentSession[] AppointmentSession
        {
            get
            {
                return this.appointmentSessionField;
            }
            set
            {
                this.appointmentSessionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AppointmentSessionListAppointmentSession
    {

        private ushort dBIDField;

        private string nameField;

        private string dateField;

        private System.DateTime startTimeField;

        private System.DateTime endTimeField;

        private System.DateTime slotLengthField;

        private AppointmentSessionListAppointmentSessionSlotTypeList slotTypeListField;

        private AppointmentSessionListAppointmentSessionSite siteField;

        private AppointmentSessionListAppointmentSessionHolderList holderListField;

        /// <remarks/>
        public ushort DBID
        {
            get
            {
                return this.dBIDField;
            }
            set
            {
                this.dBIDField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime SlotLength
        {
            get
            {
                return this.slotLengthField;
            }
            set
            {
                this.slotLengthField = value;
            }
        }

        /// <remarks/>
        public AppointmentSessionListAppointmentSessionSlotTypeList SlotTypeList
        {
            get
            {
                return this.slotTypeListField;
            }
            set
            {
                this.slotTypeListField = value;
            }
        }

        /// <remarks/>
        public AppointmentSessionListAppointmentSessionSite Site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }

        /// <remarks/>
        public AppointmentSessionListAppointmentSessionHolderList HolderList
        {
            get
            {
                return this.holderListField;
            }
            set
            {
                this.holderListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AppointmentSessionListAppointmentSessionSlotTypeList
    {

        private AppointmentSessionListAppointmentSessionSlotTypeListSlotType slotTypeField;

        /// <remarks/>
        public AppointmentSessionListAppointmentSessionSlotTypeListSlotType SlotType
        {
            get
            {
                return this.slotTypeField;
            }
            set
            {
                this.slotTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AppointmentSessionListAppointmentSessionSlotTypeListSlotType
    {

        private string typeIDField;

        private string descriptionField;

        private byte totalField;

        private byte bookedField;

        private byte blockedField;

        private byte embargoedField;

        private byte availableField;

        /// <remarks/>
        public string TypeID
        {
            get
            {
                return this.typeIDField;
            }
            set
            {
                this.typeIDField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public byte Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }

        /// <remarks/>
        public byte Booked
        {
            get
            {
                return this.bookedField;
            }
            set
            {
                this.bookedField = value;
            }
        }

        /// <remarks/>
        public byte Blocked
        {
            get
            {
                return this.blockedField;
            }
            set
            {
                this.blockedField = value;
            }
        }

        /// <remarks/>
        public byte Embargoed
        {
            get
            {
                return this.embargoedField;
            }
            set
            {
                this.embargoedField = value;
            }
        }

        /// <remarks/>
        public byte Available
        {
            get
            {
                return this.availableField;
            }
            set
            {
                this.availableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AppointmentSessionListAppointmentSessionSite
    {

        private ushort dBIDField;

        private string nameField;

        /// <remarks/>
        public ushort DBID
        {
            get
            {
                return this.dBIDField;
            }
            set
            {
                this.dBIDField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AppointmentSessionListAppointmentSessionHolderList
    {

        private AppointmentSessionListAppointmentSessionHolderListHolder holderField;

        /// <remarks/>
        public AppointmentSessionListAppointmentSessionHolderListHolder Holder
        {
            get
            {
                return this.holderField;
            }
            set
            {
                this.holderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AppointmentSessionListAppointmentSessionHolderListHolder
    {

        private ushort dBIDField;

        private ushort refIDField;

        private string titleField;

        private string firstNamesField;

        private string lastNameField;

        /// <remarks/>
        public ushort DBID
        {
            get
            {
                return this.dBIDField;
            }
            set
            {
                this.dBIDField = value;
            }
        }

        /// <remarks/>
        public ushort RefID
        {
            get
            {
                return this.refIDField;
            }
            set
            {
                this.refIDField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string FirstNames
        {
            get
            {
                return this.firstNamesField;
            }
            set
            {
                this.firstNamesField = value;
            }
        }

        /// <remarks/>
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
    }
}