// <auto-generated />
namespace EMIS.PatientFlow.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class nugetupdateaspnetidentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nugetupdateaspnetidentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201502091708033_nuget-update-aspnet-identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
