//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIS.PatientFlow.API.TopasServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClinicDetail", Namespace="http://www.cambric.co.uk/")]
    [System.SerializableAttribute()]
    public partial class ClinicDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ClinicIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClinicStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClinicNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClinicDescriptionPatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClinicDescriptionHospitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMIS.PatientFlow.API.TopasServiceReference.ClinicianInfo[] ResponsibleClinicianListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMIS.PatientFlow.API.TopasServiceReference.ClinicianInfo[] AttendingClinicianListField;
        
        private System.DateTime ClinicDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ClinicID {
            get {
                return this.ClinicIDField;
            }
            set {
                if ((this.ClinicIDField.Equals(value) != true)) {
                    this.ClinicIDField = value;
                    this.RaisePropertyChanged("ClinicID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClinicStatus {
            get {
                return this.ClinicStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ClinicStatusField, value) != true)) {
                    this.ClinicStatusField = value;
                    this.RaisePropertyChanged("ClinicStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Reception {
            get {
                return this.ReceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceptionField, value) != true)) {
                    this.ReceptionField = value;
                    this.RaisePropertyChanged("Reception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ClinicName {
            get {
                return this.ClinicNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClinicNameField, value) != true)) {
                    this.ClinicNameField = value;
                    this.RaisePropertyChanged("ClinicName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ClinicDescriptionPatient {
            get {
                return this.ClinicDescriptionPatientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClinicDescriptionPatientField, value) != true)) {
                    this.ClinicDescriptionPatientField = value;
                    this.RaisePropertyChanged("ClinicDescriptionPatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ClinicDescriptionHospital {
            get {
                return this.ClinicDescriptionHospitalField;
            }
            set {
                if ((object.ReferenceEquals(this.ClinicDescriptionHospitalField, value) != true)) {
                    this.ClinicDescriptionHospitalField = value;
                    this.RaisePropertyChanged("ClinicDescriptionHospital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public EMIS.PatientFlow.API.TopasServiceReference.ClinicianInfo[] ResponsibleClinicianList {
            get {
                return this.ResponsibleClinicianListField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsibleClinicianListField, value) != true)) {
                    this.ResponsibleClinicianListField = value;
                    this.RaisePropertyChanged("ResponsibleClinicianList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public EMIS.PatientFlow.API.TopasServiceReference.ClinicianInfo[] AttendingClinicianList {
            get {
                return this.AttendingClinicianListField;
            }
            set {
                if ((object.ReferenceEquals(this.AttendingClinicianListField, value) != true)) {
                    this.AttendingClinicianListField = value;
                    this.RaisePropertyChanged("AttendingClinicianList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime ClinicDateTime {
            get {
                return this.ClinicDateTimeField;
            }
            set {
                if ((this.ClinicDateTimeField.Equals(value) != true)) {
                    this.ClinicDateTimeField = value;
                    this.RaisePropertyChanged("ClinicDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClinicianInfo", Namespace="http://www.cambric.co.uk/")]
    [System.SerializableAttribute()]
    public partial class ClinicianInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ForenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Forename {
            get {
                return this.ForenameField;
            }
            set {
                if ((object.ReferenceEquals(this.ForenameField, value) != true)) {
                    this.ForenameField = value;
                    this.RaisePropertyChanged("Forename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppointmentDetail", Namespace="http://www.cambric.co.uk/")]
    [System.SerializableAttribute()]
    public partial class AppointmentDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SlotIDField;
        
        private int ClinicIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SlotStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMIS.PatientFlow.API.TopasServiceReference.ClinicDetail ClinicInfoField;
        
        private System.DateTime AppointmentDateTimeField;
        
        private System.DateTime CheckInDateTimeField;
        
        private System.DateTime CheckOutDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HospitalNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CHIField;
        
        private System.DateTime DoBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ForenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SlotID {
            get {
                return this.SlotIDField;
            }
            set {
                if ((this.SlotIDField.Equals(value) != true)) {
                    this.SlotIDField = value;
                    this.RaisePropertyChanged("SlotID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ClinicID {
            get {
                return this.ClinicIDField;
            }
            set {
                if ((this.ClinicIDField.Equals(value) != true)) {
                    this.ClinicIDField = value;
                    this.RaisePropertyChanged("ClinicID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SlotStatus {
            get {
                return this.SlotStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SlotStatusField, value) != true)) {
                    this.SlotStatusField = value;
                    this.RaisePropertyChanged("SlotStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public EMIS.PatientFlow.API.TopasServiceReference.ClinicDetail ClinicInfo {
            get {
                return this.ClinicInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClinicInfoField, value) != true)) {
                    this.ClinicInfoField = value;
                    this.RaisePropertyChanged("ClinicInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime AppointmentDateTime {
            get {
                return this.AppointmentDateTimeField;
            }
            set {
                if ((this.AppointmentDateTimeField.Equals(value) != true)) {
                    this.AppointmentDateTimeField = value;
                    this.RaisePropertyChanged("AppointmentDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime CheckInDateTime {
            get {
                return this.CheckInDateTimeField;
            }
            set {
                if ((this.CheckInDateTimeField.Equals(value) != true)) {
                    this.CheckInDateTimeField = value;
                    this.RaisePropertyChanged("CheckInDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime CheckOutDateTime {
            get {
                return this.CheckOutDateTimeField;
            }
            set {
                if ((this.CheckOutDateTimeField.Equals(value) != true)) {
                    this.CheckOutDateTimeField = value;
                    this.RaisePropertyChanged("CheckOutDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string HospitalNumber {
            get {
                return this.HospitalNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.HospitalNumberField, value) != true)) {
                    this.HospitalNumberField = value;
                    this.RaisePropertyChanged("HospitalNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CHI {
            get {
                return this.CHIField;
            }
            set {
                if ((object.ReferenceEquals(this.CHIField, value) != true)) {
                    this.CHIField = value;
                    this.RaisePropertyChanged("CHI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime DoB {
            get {
                return this.DoBField;
            }
            set {
                if ((this.DoBField.Equals(value) != true)) {
                    this.DoBField = value;
                    this.RaisePropertyChanged("DoB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Forename {
            get {
                return this.ForenameField;
            }
            set {
                if ((object.ReferenceEquals(this.ForenameField, value) != true)) {
                    this.ForenameField = value;
                    this.RaisePropertyChanged("Forename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Address3 {
            get {
                return this.Address3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address3Field, value) != true)) {
                    this.Address3Field = value;
                    this.RaisePropertyChanged("Address3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Address4 {
            get {
                return this.Address4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address4Field, value) != true)) {
                    this.Address4Field = value;
                    this.RaisePropertyChanged("Address4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TopasServiceReference.TestKioskSoap")]
    public interface TestKioskSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        EMIS.PatientFlow.API.TopasServiceReference.HelloWorldResponse HelloWorld(EMIS.PatientFlow.API.TopasServiceReference.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public EMIS.PatientFlow.API.TopasServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(EMIS.PatientFlow.API.TopasServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public EMIS.PatientFlow.API.TopasServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(EMIS.PatientFlow.API.TopasServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TestKioskSoapChannel : EMIS.PatientFlow.API.TopasServiceReference.TestKioskSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestKioskSoapClient : System.ServiceModel.ClientBase<EMIS.PatientFlow.API.TopasServiceReference.TestKioskSoap>, EMIS.PatientFlow.API.TopasServiceReference.TestKioskSoap {
        
        public TestKioskSoapClient() {
        }
        
        public TestKioskSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestKioskSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestKioskSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestKioskSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EMIS.PatientFlow.API.TopasServiceReference.HelloWorldResponse EMIS.PatientFlow.API.TopasServiceReference.TestKioskSoap.HelloWorld(EMIS.PatientFlow.API.TopasServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            EMIS.PatientFlow.API.TopasServiceReference.HelloWorldRequest inValue = new EMIS.PatientFlow.API.TopasServiceReference.HelloWorldRequest();
            inValue.Body = new EMIS.PatientFlow.API.TopasServiceReference.HelloWorldRequestBody();
            EMIS.PatientFlow.API.TopasServiceReference.HelloWorldResponse retVal = ((EMIS.PatientFlow.API.TopasServiceReference.TestKioskSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cambric.co.uk/", ConfigurationName="TopasServiceReference.KioskSoap")]
    public interface KioskSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://www.cambric.co.uk/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cambric.co.uk/GetClinicSessions", ReplyAction="*")]
        EMIS.PatientFlow.API.TopasServiceReference.GetClinicSessionsResponse GetClinicSessions(EMIS.PatientFlow.API.TopasServiceReference.GetClinicSessionsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://www.cambric.co.uk/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cambric.co.uk/GetClinicAppointments", ReplyAction="*")]
        EMIS.PatientFlow.API.TopasServiceReference.GetClinicAppointmentsResponse GetClinicAppointments(EMIS.PatientFlow.API.TopasServiceReference.GetClinicAppointmentsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://www.cambric.co.uk/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cambric.co.uk/CheckIn", ReplyAction="*")]
        EMIS.PatientFlow.API.TopasServiceReference.CheckInResponse CheckIn(EMIS.PatientFlow.API.TopasServiceReference.CheckInRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClinicSessionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClinicSessions", Namespace="http://www.cambric.co.uk/", Order=0)]
        public EMIS.PatientFlow.API.TopasServiceReference.GetClinicSessionsRequestBody Body;
        
        public GetClinicSessionsRequest() {
        }
        
        public GetClinicSessionsRequest(EMIS.PatientFlow.API.TopasServiceReference.GetClinicSessionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cambric.co.uk/")]
    public partial class GetClinicSessionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string clinicset;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime startDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime endDateTime;
        
        public GetClinicSessionsRequestBody() {
        }
        
        public GetClinicSessionsRequestBody(string username, string password, string clinicset, System.DateTime startDateTime, System.DateTime endDateTime) {
            this.username = username;
            this.password = password;
            this.clinicset = clinicset;
            this.startDateTime = startDateTime;
            this.endDateTime = endDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClinicSessionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClinicSessionsResponse", Namespace="http://www.cambric.co.uk/", Order=0)]
        public EMIS.PatientFlow.API.TopasServiceReference.GetClinicSessionsResponseBody Body;
        
        public GetClinicSessionsResponse() {
        }
        
        public GetClinicSessionsResponse(EMIS.PatientFlow.API.TopasServiceReference.GetClinicSessionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cambric.co.uk/")]
    public partial class GetClinicSessionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EMIS.PatientFlow.API.TopasServiceReference.ClinicDetail[] GetClinicSessionsResult;
        
        public GetClinicSessionsResponseBody() {
        }
        
        public GetClinicSessionsResponseBody(EMIS.PatientFlow.API.TopasServiceReference.ClinicDetail[] GetClinicSessionsResult) {
            this.GetClinicSessionsResult = GetClinicSessionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClinicAppointmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClinicAppointments", Namespace="http://www.cambric.co.uk/", Order=0)]
        public EMIS.PatientFlow.API.TopasServiceReference.GetClinicAppointmentsRequestBody Body;
        
        public GetClinicAppointmentsRequest() {
        }
        
        public GetClinicAppointmentsRequest(EMIS.PatientFlow.API.TopasServiceReference.GetClinicAppointmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cambric.co.uk/")]
    public partial class GetClinicAppointmentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string clinicset;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime startDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime endDateTime;
        
        public GetClinicAppointmentsRequestBody() {
        }
        
        public GetClinicAppointmentsRequestBody(string username, string password, string clinicset, System.DateTime startDateTime, System.DateTime endDateTime) {
            this.username = username;
            this.password = password;
            this.clinicset = clinicset;
            this.startDateTime = startDateTime;
            this.endDateTime = endDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClinicAppointmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClinicAppointmentsResponse", Namespace="http://www.cambric.co.uk/", Order=0)]
        public EMIS.PatientFlow.API.TopasServiceReference.GetClinicAppointmentsResponseBody Body;
        
        public GetClinicAppointmentsResponse() {
        }
        
        public GetClinicAppointmentsResponse(EMIS.PatientFlow.API.TopasServiceReference.GetClinicAppointmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cambric.co.uk/")]
    public partial class GetClinicAppointmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EMIS.PatientFlow.API.TopasServiceReference.AppointmentDetail[] GetClinicAppointmentsResult;
        
        public GetClinicAppointmentsResponseBody() {
        }
        
        public GetClinicAppointmentsResponseBody(EMIS.PatientFlow.API.TopasServiceReference.AppointmentDetail[] GetClinicAppointmentsResult) {
            this.GetClinicAppointmentsResult = GetClinicAppointmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckIn", Namespace="http://www.cambric.co.uk/", Order=0)]
        public EMIS.PatientFlow.API.TopasServiceReference.CheckInRequestBody Body;
        
        public CheckInRequest() {
        }
        
        public CheckInRequest(EMIS.PatientFlow.API.TopasServiceReference.CheckInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cambric.co.uk/")]
    public partial class CheckInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int slotID;
        
        public CheckInRequestBody() {
        }
        
        public CheckInRequestBody(string username, string password, int slotID) {
            this.username = username;
            this.password = password;
            this.slotID = slotID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckInResponse", Namespace="http://www.cambric.co.uk/", Order=0)]
        public EMIS.PatientFlow.API.TopasServiceReference.CheckInResponseBody Body;
        
        public CheckInResponse() {
        }
        
        public CheckInResponse(EMIS.PatientFlow.API.TopasServiceReference.CheckInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CheckInResponseBody {
        
        public CheckInResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KioskSoapChannel : EMIS.PatientFlow.API.TopasServiceReference.KioskSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KioskSoapClient : System.ServiceModel.ClientBase<EMIS.PatientFlow.API.TopasServiceReference.KioskSoap>, EMIS.PatientFlow.API.TopasServiceReference.KioskSoap {
        
        public KioskSoapClient() {
        }
        
        public KioskSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KioskSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KioskSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KioskSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EMIS.PatientFlow.API.TopasServiceReference.GetClinicSessionsResponse EMIS.PatientFlow.API.TopasServiceReference.KioskSoap.GetClinicSessions(EMIS.PatientFlow.API.TopasServiceReference.GetClinicSessionsRequest request) {
            return base.Channel.GetClinicSessions(request);
        }
        
        public EMIS.PatientFlow.API.TopasServiceReference.ClinicDetail[] GetClinicSessions(string username, string password, string clinicset, System.DateTime startDateTime, System.DateTime endDateTime) {
            EMIS.PatientFlow.API.TopasServiceReference.GetClinicSessionsRequest inValue = new EMIS.PatientFlow.API.TopasServiceReference.GetClinicSessionsRequest();
            inValue.Body = new EMIS.PatientFlow.API.TopasServiceReference.GetClinicSessionsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.clinicset = clinicset;
            inValue.Body.startDateTime = startDateTime;
            inValue.Body.endDateTime = endDateTime;
            EMIS.PatientFlow.API.TopasServiceReference.GetClinicSessionsResponse retVal = ((EMIS.PatientFlow.API.TopasServiceReference.KioskSoap)(this)).GetClinicSessions(inValue);
            return retVal.Body.GetClinicSessionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EMIS.PatientFlow.API.TopasServiceReference.GetClinicAppointmentsResponse EMIS.PatientFlow.API.TopasServiceReference.KioskSoap.GetClinicAppointments(EMIS.PatientFlow.API.TopasServiceReference.GetClinicAppointmentsRequest request) {
            return base.Channel.GetClinicAppointments(request);
        }
        
        public EMIS.PatientFlow.API.TopasServiceReference.AppointmentDetail[] GetClinicAppointments(string username, string password, string clinicset, System.DateTime startDateTime, System.DateTime endDateTime) {
            EMIS.PatientFlow.API.TopasServiceReference.GetClinicAppointmentsRequest inValue = new EMIS.PatientFlow.API.TopasServiceReference.GetClinicAppointmentsRequest();
            inValue.Body = new EMIS.PatientFlow.API.TopasServiceReference.GetClinicAppointmentsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.clinicset = clinicset;
            inValue.Body.startDateTime = startDateTime;
            inValue.Body.endDateTime = endDateTime;
            EMIS.PatientFlow.API.TopasServiceReference.GetClinicAppointmentsResponse retVal = ((EMIS.PatientFlow.API.TopasServiceReference.KioskSoap)(this)).GetClinicAppointments(inValue);
            return retVal.Body.GetClinicAppointmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EMIS.PatientFlow.API.TopasServiceReference.CheckInResponse EMIS.PatientFlow.API.TopasServiceReference.KioskSoap.CheckIn(EMIS.PatientFlow.API.TopasServiceReference.CheckInRequest request) {
            return base.Channel.CheckIn(request);
        }
        
        public void CheckIn(string username, string password, int slotID) {
            EMIS.PatientFlow.API.TopasServiceReference.CheckInRequest inValue = new EMIS.PatientFlow.API.TopasServiceReference.CheckInRequest();
            inValue.Body = new EMIS.PatientFlow.API.TopasServiceReference.CheckInRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.slotID = slotID;
            EMIS.PatientFlow.API.TopasServiceReference.CheckInResponse retVal = ((EMIS.PatientFlow.API.TopasServiceReference.KioskSoap)(this)).CheckIn(inValue);
        }
    }
}
