//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace GetPatientRecordDetails {
    using System.Xml.Serialization;




	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class ClientIntegrationRequest
	{

		private string aPIKeyField;

		private string deviceIDField;

		private string deviceVersionField;

		private string requestUIDField;

		private string functionField;

		private decimal functionVersionField;

		private ClientIntegrationRequestFunctionParameters functionParametersField;

		public ClientIntegrationRequest()
		{
			this.functionField = "GetPatientRecord";
			this.functionVersionField = ((decimal)(1m));
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string APIKey
		{
			get
			{
				return this.aPIKeyField;
			}
			set
			{
				this.aPIKeyField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string DeviceID
		{
			get
			{
				return this.deviceIDField;
			}
			set
			{
				this.deviceIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string DeviceVersion
		{
			get
			{
				return this.deviceVersionField;
			}
			set
			{
				this.deviceVersionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string RequestUID
		{
			get
			{
				return this.requestUIDField;
			}
			set
			{
				this.requestUIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Function
		{
			get
			{
				return this.functionField;
			}
			set
			{
				this.functionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal FunctionVersion
		{
			get
			{
				return this.functionVersionField;
			}
			set
			{
				this.functionVersionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ClientIntegrationRequestFunctionParameters FunctionParameters
		{
			get
			{
				return this.functionParametersField;
			}
			set
			{
				this.functionParametersField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ClientIntegrationRequestFunctionParameters
	{

		private ClientIntegrationRequestFunctionParametersIdentity identityField;

		private ClientIntegrationRequestFunctionParametersFilter filterField;

		private ClientIntegrationRequestFunctionParametersLeaveRecordOpen leaveRecordOpenField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ClientIntegrationRequestFunctionParametersIdentity Identity
		{
			get
			{
				return this.identityField;
			}
			set
			{
				this.identityField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ClientIntegrationRequestFunctionParametersFilter Filter
		{
			get
			{
				return this.filterField;
			}
			set
			{
				this.filterField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ClientIntegrationRequestFunctionParametersLeaveRecordOpen LeaveRecordOpen
		{
			get
			{
				return this.leaveRecordOpenField;
			}
			set
			{
				this.leaveRecordOpenField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ClientIntegrationRequestFunctionParametersIdentity
	{

		private string nHSNumberField;

		private string pseudoNumberField;

		private string clientIDField;

		private string strategicReportingIdentifierField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string NHSNumber
		{
			get
			{
				return this.nHSNumberField;
			}
			set
			{
				this.nHSNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string PseudoNumber
		{
			get
			{
				return this.pseudoNumberField;
			}
			set
			{
				this.pseudoNumberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string ClientID
		{
			get
			{
				return this.clientIDField;
			}
			set
			{
				this.clientIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string StrategicReportingIdentifier
		{
			get
			{
				return this.strategicReportingIdentifierField;
			}
			set
			{
				this.strategicReportingIdentifierField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ClientIntegrationRequestFunctionParametersFilter
	{

		private ClientIntegrationRequestFunctionParametersFilterDemographics demographicsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ClientIntegrationRequestFunctionParametersFilterDemographics Demographics
		{
			get
			{
				return this.demographicsField;
			}
			set
			{
				this.demographicsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ClientIntegrationRequestFunctionParametersFilterDemographics
	{
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ClientIntegrationRequestFunctionParametersLeaveRecordOpen
	{
	}


}
